[package]
name = "markup_language"
version = "0.1.0"
authors = ["Laysa Uchoa <laysa.uchoa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
